use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// --- Identifiers ---

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ContextEntryId(pub String);

// --- Context Kind ---

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContextKind {
    /// Team-shared agent configuration: CLAUDE.md, runbooks, conventions
    Config,
    /// Point-in-time board/project snapshots
    Snapshot,
    /// Arbitrary docs: specs, decisions, feedback, notes, code
    Document,
}

impl ContextKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Config => "config",
            Self::Snapshot => "snapshot",
            Self::Document => "document",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "config" => Some(Self::Config),
            "snapshot" => Some(Self::Snapshot),
            "document" => Some(Self::Document),
            _ => None,
        }
    }

    /// Filesystem subdirectory for this kind.
    pub fn dir_name(&self) -> &'static str {
        self.as_str()
    }
}

// --- Context Source ---

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContextSource {
    /// Manually added by a human via CLI or API
    Human,
    /// Added by an agent session
    Agent { session_id: String },
    /// Generated by a kernel subsystem (e.g., board snapshot)
    System { subsystem: String },
    /// Imported from gctrl-net crawl
    Crawl { domain: String },
}

impl ContextSource {
    pub fn source_type(&self) -> &'static str {
        match self {
            Self::Human => "human",
            Self::Agent { .. } => "agent",
            Self::System { .. } => "system",
            Self::Crawl { .. } => "crawl",
        }
    }

    pub fn source_ref(&self) -> Option<&str> {
        match self {
            Self::Human => None,
            Self::Agent { session_id } => Some(session_id),
            Self::System { subsystem } => Some(subsystem),
            Self::Crawl { domain } => Some(domain),
        }
    }

    pub fn from_parts(source_type: &str, source_ref: Option<&str>) -> Self {
        match source_type {
            "agent" => Self::Agent {
                session_id: source_ref.unwrap_or("").to_string(),
            },
            "system" => Self::System {
                subsystem: source_ref.unwrap_or("").to_string(),
            },
            "crawl" => Self::Crawl {
                domain: source_ref.unwrap_or("").to_string(),
            },
            _ => Self::Human,
        }
    }
}

// --- Context Entry ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextEntry {
    pub id: ContextEntryId,
    pub kind: ContextKind,
    /// Relative path within context store, e.g. "runbooks/deploy.md"
    pub path: String,
    pub title: String,
    pub source: ContextSource,
    pub word_count: usize,
    /// SHA-256 of content for dedup/change detection
    pub content_hash: String,
    pub tags: Vec<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub synced: bool,
}

// --- Filter ---

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContextFilter {
    pub kind: Option<ContextKind>,
    pub tag: Option<String>,
    pub source: Option<String>,
    pub search: Option<String>,
    pub limit: Option<usize>,
}

// --- Stats ---

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContextStats {
    pub total_entries: u64,
    pub total_words: u64,
    pub by_kind: Vec<(String, u64)>,
    pub by_source: Vec<(String, u64)>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn context_kind_roundtrip() {
        let kinds = [ContextKind::Config, ContextKind::Snapshot, ContextKind::Document];
        for kind in &kinds {
            let s = kind.as_str();
            let parsed = ContextKind::from_str(s).unwrap();
            assert_eq!(&parsed, kind);
        }
    }

    #[test]
    fn context_kind_unknown_returns_none() {
        assert!(ContextKind::from_str("unknown").is_none());
    }

    #[test]
    fn context_source_parts_roundtrip() {
        let sources = vec![
            ContextSource::Human,
            ContextSource::Agent { session_id: "s1".into() },
            ContextSource::System { subsystem: "board".into() },
            ContextSource::Crawl { domain: "docs.example.com".into() },
        ];
        for src in &sources {
            let rebuilt = ContextSource::from_parts(src.source_type(), src.source_ref());
            assert_eq!(rebuilt.source_type(), src.source_type());
        }
    }

    #[test]
    fn context_entry_serialization() {
        let entry = ContextEntry {
            id: ContextEntryId("ctx-1".into()),
            kind: ContextKind::Document,
            path: "notes/test.md".into(),
            title: "Test Note".into(),
            source: ContextSource::Human,
            word_count: 42,
            content_hash: "abc123".into(),
            tags: vec!["test".into()],
            created_at: Utc::now(),
            updated_at: Utc::now(),
            synced: false,
        };
        let json = serde_json::to_string(&entry).unwrap();
        let parsed: ContextEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.id, entry.id);
        assert_eq!(parsed.path, entry.path);
    }
}
